[KT3-06] Cria consulta
devpass-tech/challenge-hexagonal-backend pull request #10
Opened 2022-09-05 19:54 UTC by RiellyCM

## Descrição 

Criar consulta para a primeira transação do dia. Cria a função getFirstTransactionByDate no adapter, utilizando Spring Data a fim de retornar a primeira transação realizada, a partir de uma conta e data que serão passadas como parâmetro. Caso a conta não tenha transações, deverá retornar nulo (transaction?)

## Critérios de aceitação:

- [X]  Função criada no adapter
- [X]  Tratamento e mapeamento da entidade para o objeto de domínio

2022-09-05 20:53 UTC, michel05 requested changes

2022-09-05 20:53 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/database/client/TransactionSpringDataRepository.kt
> +
A nossa consulta vai precisar passar um range de data para que o SQL gere algo assim:
SELECT *
FROM xyz
WHERE abc BETWEEN CAST('2022-08-01' AS DATETIME) AND CAST('2022-08-02' AS DATETIME);

2022-09-05 20:53 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/TransactionAdapterRepository.kt
O tipo da "date" que estamos esperando será apenas um LocalDate, pois não passaremos o time.
Ex.: 2022-08-05

E ao chamar o repository precisaremos passar o range esperado

2022-09-06 19:55 UTC, michel05 requested changes

2022-09-06 19:55 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/database/client/TransactionSpringDataRepository.kt
> +
@RiellyCM nesse caso nós precisaremos da primeira transaction do dia.
Nosso SQL precisará ser mais ou menos assim:
Select * from transaction 
where account_id = ?
and transaction_date between ? and ?
limit 1

Para representar isso via Spring Data, precisamos que o método siga o seguinte padrão:
fun findTopByAccountIdAndTransactionDateBetweenOrderByTransactionDateAsc(
    accountId: Long,
    startDate: LocalDateTime,
    endDate: LocalDateTime
) : Transaction?

findTop -> buscará o primeiro resultado da consulta (limit 1)
by -> representa nossa cláusula 'Where'
accountId -> filtra pela accountId (account_id = ?)
AndTransactionDateBetween -> cria o filtro da data (and transaction_date between ? and ?)
OrderByTransactionDateAsc -> ordena nossa consulta pela transaction_date em ordem crescente

Vamos abordar isso no nosso encontro para ficar claro para todos :)

2022-09-06 21:46 UTC, michel05 requested changes

2022-09-06 21:46 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/domain/ports/TransactionRepositoryPort.kt
> +
getFirstTransactionByDate() {
accountId: Long,
date: LacalDate
}

2022-09-06 21:46 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/TransactionAdapterRepository.kt
> +
fun getFirstTransactionByDateRange(accountId: Long, date: LocalDate): Transaction? {
        val startOfDay = date.atStartOfDay() // 00:00
        val startOfTheNextDay = date.plusDays(1).atStartOfDay() // 07/09/22 00:00
        return repository.findTopByAccountIdAndTransactionDateBetweenOrderByTransactionDateAsc(accountId, startOfDay, startOfTheNextDay)?.toDomain()
    }

2022-09-06 22:16 UTC, RiellyCM commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/TransactionAdapterRepository.kt
> +
@michel05 Quando eu implemento essas novas variáveis ele dá erro, dizendo que precisa ser um localDateTime 
![image](https://user-images.githubusercontent.com/29679646/188749659-60136b46-fb27-464a-a50a-325eaf962405.png)

![image](https://user-images.githubusercontent.com/29679646/188749701-820e8836-4f80-45f6-a048-fb59e12fa156.png)

e também sugere a implementação de startOfTheNextDay na  TransactionSpringDataRepository

2022-09-06 22:16 UTC, RiellyCM commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/TransactionAdapterRepository.kt
> +
isso está correto?

2022-09-07 21:03 UTC, michel05 approved these changes
Boa!!

2022-09-07 21:04 UTC, merged