[KT3-11] Implementar Regra: Conta inativa
devpass-tech/challenge-hexagonal-backend pull request #12
Opened 2022-09-06 19:36 UTC by elainemattos

### Descrição

Deve validar se a conta está ativa, caso não estiver ativa, adicionar o violação: Violation.ACCOUNT_NOT_ACTIVE (account-not-active) no objeto ValidationResult

## Critérios de aceitação:

- [ ]  Regra criada corretamente e validada
- [ ]  Adicionar script migration campo active: boolean

2022-09-06 19:41 UTC, michel05 requested changes

2022-09-06 19:41 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/domain/service/rules/ActiveAccountRule.kt
> +
@elainemattos nesse caso, não precisaremos buscar a Account no Banco.
Quem chamar essa função validate já vai ter feito essa consulta em algum momento anterior, ou seja, a account já vai estar populada corretamente ;)

2022-09-06 19:46 UTC, elainemattos commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/domain/service/rules/ActiveAccountRule.kt
> +
neste caso entao removo o arquivo AccountRepositoryPort tb @michel05 ?

2022-09-07 14:32 UTC, michel05 requested changes

2022-09-07 14:32 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/domain/service/rules/ActiveAccountRule.kt
> +
@elainemattos aqui só faltou o @Service para o Spring saber injetar essa depedência em outras classes

2022-09-07 20:55 UTC, michel05 approved these changes

2022-09-07 20:56 UTC, merged