[KT3-13] Implementa regra do limite de transação para a conta
devpass-tech/challenge-hexagonal-backend pull request #17
Opened 2022-09-08 20:28 UTC by t4lu

Deve validar se já há transações registradas no mesmo dia 

→ caso negativo, validar se a mesma supera 80% do saldo atual.

Caso não atender a regra, adicionar o violação no objeto ValidationResult: 

Violation.HIGH_TRANSACTION_VALUE

## Critérios de aceitação:

- [ ]  Regra criada corretamente e validada

2022-09-08 21:15 UTC, michel05 requested changes

2022-09-08 21:15 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/database/client/TransactionSpringDataRepository.kt
> +
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation

findByAccountIdAndTransactionDateTimeBetween

2022-09-08 22:12 UTC, michel05 requested changes

2022-09-08 22:12 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/database/client/TransactionSpringDataRepository.kt
> +
@t4lu a funcao que precisa add o Between é a dessa classe ;)

findByAccountIdAndTransactionDateTimeBetween

2022-09-08 22:12 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/TransactionAdapterRepository.kt
> +
Aqui estava correto o nome: getTransactionByDateTime

2022-09-09 18:29 UTC, t4lu commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/database/client/TransactionSpringDataRepository.kt
> +
ops, desculpe kkkkk corrigi :D

2022-09-09 18:41 UTC, michel05 approved these changes

2022-09-09 18:41 UTC, merged