[WIP] Criado endpoint para Listar situação dos clientes
devpass-tech/challenge-hexagonal-backend pull request #20
Opened 2022-09-09 20:39 UTC by livioqueiroz

Endpoint criado, porém duas dúvidas:
1 - Apesar de entender a função do DTO, não sei como iria fazê-lo nesse caso, já que não tratar nenhum dado que receberia da request
2 - No adapter preciso converter ClientEntity para Client, porém, Client possui uma Account e aí precisaria converter essa para o domínio também. Até fiz as funções, mas não sei como fazê-las funcionar.

2022-09-09 20:39 UTC, livioqueiroz commented
Endpoint criado, porém duas dúvidas:
1 - Apesar de entender a função do DTO, não sei como iria fazê-lo nesse caso, já que não tratar nenhum dado que receberia da request
2 - No adapter preciso converter ClientEntity para Client, porém, Client possui uma Account e aí precisaria converter essa para o domínio também. Até fiz as funções, mas não sei como fazê-las funcionar.

2022-09-09 22:00 UTC, michel05 requested changes

2022-09-09 22:00 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/entity/ClientEntity.kt
> +) {
fun toDomain() = Client(name = this.name, birthDate = this.birthDate, account = this.account.toDomain())

2022-09-09 22:00 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/ClientAdapterRepository.kt
> -        TODO("Not yet implemented")
repository.findAll().map { it.toDomain() }

2022-09-09 22:00 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/application/controller/ClientController.kt
> +    @GetMapping
@GetMapping("/city/{city}")
    fun getAllClients(): List<ClientDtoResponse> {
        val clients : List<Client> =  clientManagerServicePort.listClients()
        return clients.map { ClientDtoResponse(it) }
    }

2022-09-09 22:00 UTC, michel05 commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/application/controller/ClientController.kt
> +    @GetMapping
data class ClientDtoResponse(
    val name: String,
    val balance: BigDecimal
) {
    constructor(client: Client) : this(
        name = client.name,
        balance = client.account.balance.toBigDecimal()
    )
}

2022-09-12 17:04 UTC, livioqueiroz commented on solutions/devsprint-michel-ferreira-1/src/main/kotlin/com/devpass/challengehexagonal/resources/repository/entity/AccountEntity.kt
> +    fun toDomain() = Account(accountNumber = this.accountNumber, balance = this.balance.toDouble(), active = true)
Aqui eu não consigo criar o objeto de Account, porque precisa de outros campos que não tenho, como: "active" e "TransactionHistory" @michel05

2022-09-12 18:11 UTC, michel05 approved these changes
Show de bola!

2022-09-12 18:11 UTC, merged