[KT3-05] Criar migration (V3), entity, e repository para credit card invoice
devpass-tech/challenge-hexagonal-backend pull request #22
Opened 2022-09-15 17:37 UTC by marianaccn

## O que é

Precisamos preparar a infraestrutura de acesso à dados do nosso service às faturas de cartões de crédito. Para isso, crie a `CreditCardInvoiceEntity`, e também gere uma migração para criar a tabela.

### **Importante: A estrutura da tabela está no [README.md](http://readme.md/)**

Implementação inteira no package `data`.

## Critérios de aceite:

- [ ]  Entity complementada respeita os campos definidos no `README.md`
- [ ]  Campos da entity refletem os campos definidos no `README.md`
- [ ]  Migration criada e sinalizada como V3

2022-09-15 22:40 UTC, Incognitowski requested changes

2022-09-15 22:40 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/data/entities/CreditCardInvoiceEntity.kt
> +    val paitAt: LocalDateTime? = LocalDateTime.now()
Alterar de "val" pra "var" e corrigir typo no campo "paidAt" (está "paitAt").

Remover @CreationTimestamp da linha 16. Campo paidAt começa como nulo!

2022-09-15 22:40 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/data/repositories/CreditCardInvoiceRepository.kt
> +interface CreditCardInvoiceRepository {
Essa interface precisa estender ```CrudRepository<T,ID>```

2022-09-15 22:40 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/resources/db/migrations/V3_create_table_credit_card_invoice.sql
> +CREATE TABLE credit_card_invoice
Nome do arquivo precisa ser "V3__.....", está com um "_" só atualmente.

2022-09-16 12:55 UTC, marianaccn commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/data/repositories/CreditCardInvoiceRepository.kt
> +interface CreditCardInvoiceRepository {
Fiz o commit com a alteração mas fiquei em dúvida sobre essas refências T e ID, eles ainda não existem mesmo? Eu deveria estar importando de algum lugar ou deveria criá-las?

2022-09-19 22:07 UTC, Incognitowski approved these changes

2022-09-19 22:07 UTC, merged