[KT3-21] Implementar cobrança de cartão de crédito
devpass-tech/challenge-hexagonal-backend pull request #42
Opened 2022-09-22 22:06 UTC by livioqueiroz

2022-09-22 22:48 UTC, Incognitowski requested changes

2022-09-22 22:48 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/transport/controllers/CreditCardController.kt
> +    @PostMapping
Alterar esse método para o `CreditCardOperationController`

2022-09-22 22:48 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/transport/requests/CreditCardChargeResquest.kt
> +data class CreditCardChargeResquest(
Arrumar typo "Resquest"

2022-09-22 22:48 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/transport/requests/CreditCardChargeResquest.kt
> +    val id: String,
Pode remover o ID daqui

2022-09-22 22:48 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/transport/requests/CreditCardChargeResquest.kt
> +    val installmentValue: Double,
Gerar esse valor dentro do domain

2022-09-22 22:48 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/domain/objects/CreditCardOperation.kt
> +    var creditCardId: String,
Voltar para `creditCard` pois senão estaremos quebrando o banco de dados

2022-09-22 22:48 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/domain/objects/CreditCardCharge.kt
> +data class CreditCardCharge(
Refletir alterações feitas na request

2022-09-22 22:49 UTC, Incognitowski commented
**Exemplo do refactor que fizemos:**
![image](https://user-images.githubusercontent.com/20343569/191864697-f418550f-342c-44c1-8404-cf3245e09250.png)

2022-09-23 22:34 UTC, Incognitowski commented
CreditCardChargeRequest
  - Não pedir month e year
CreditCardOperationService
  - Refactor do processo de geração de parcelas
CreditCardDAO
  - Alterar função para update atualizando somente os campos necessários.

2022-09-26 15:46 UTC, livioqueiroz commented
@Incognitowski acho que agora foi haha

2022-09-26 21:26 UTC, Incognitowski requested changes

2022-09-26 21:26 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/domain/CreditCardOperationService.kt
> +        for (i in 1 until 12) {
O número de parcelas não é sempre 12, certo?

2022-09-26 22:19 UTC, Incognitowski approved these changes

2022-09-26 22:19 UTC, merged