WIP[KT3-19]: Cria requisição para criação de cartão.
devpass-tech/challenge-hexagonal-backend pull request #44
Opened 2022-09-23 21:18 UTC by Pedroajs

2022-09-26 18:57 UTC, Pedroajs commented
## O que é

Implemente um endpoint para solicitar a criação de um cartão de crédito.

1. Crie `CreditCardController` (caso ele não exista) dentro do package transport, ele deve pedir um `ICreditCardServiceAdapter` como parâmetro de construtor.
2. Crie uma função chamada `requestCreditCard` dentro da interface `ICreditCardServiceAdapter`.
3. Implemente a função `requestCreditCard` no `CreditCardService`. 
4. Implemente o endpoint que chama essa função no `CreditCardController`

### Regras para solicitação:

- CPF do solicitante deve ser aprovado no service anti-fraud (que também informa o limite a ser disponibilizado no cartão).
- Não podem existir dois cartões de crédito para o mesmo CPF.
- Caso o usuário seja aprovado no service de anti-fraud para receber um cartão, uma conta deve ser criada para ele utilizando o service de account-management antes que o cartão seja gerado.


## Critérios de aceite

- [x]  Regras de negócio respeitadas.
- [x]  O processo levanta erros relevantes que herdam de OwnedException.
- [x]  Arquitetura respeitada.

2022-09-26 21:32 UTC, Incognitowski requested changes

2022-09-26 21:32 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/data/CreditCardDAO.kt
> +   private val creditCard: CreditCardEntity,
Para criar um DAO é necessário uma instância de `CreditCardEntity`?

2022-09-26 21:32 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/domain/CreditCardService.kt
> +        if (eligibility.shouldHaveCreditCard)
Aqui acredito que precisa negar a operação: `!eligibility.shouldHaveCreditCard` em vez de `eligibility.shouldHaveCreditCard`

2022-09-26 21:32 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/domain/CreditCardService.kt
> +        return creditCardDAO.createCreditCard(CPF = creditCardRequest.CPF, creditLimit = proposedLimit)
E o nome impresso no cartão?

2022-09-26 22:13 UTC, Pedroajs commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/data/CreditCardDAO.kt
> +   private val creditCard: CreditCardEntity,
🤔🤔🤔🤔🤔🤔🤔

2022-09-26 22:38 UTC, Incognitowski requested changes

2022-09-26 22:38 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/data/CreditCardDAO.kt
> +    override fun createCreditCard(CPF: String,name: String, creditLimit: Double) : CreditCard {
Entre essa linha e a de baixo, você precisa criar um CreditCard utilizando as informações recebidas como argumento.

2022-09-26 22:38 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-3/src/main/kotlin/io/devpass/creditcard/domain/CreditCardService.kt
> +
Sugestão é criar o `CreditCard` aqui e na função `creditCardDAO.createCreditCard` receber uma instância de `CreditCard` em vez dos parâmetros.

2022-09-27 21:07 UTC, Incognitowski approved these changes

2022-09-27 22:15 UTC, Incognitowski approved these changes

2022-09-27 22:15 UTC, merged